### ISSUE TITLE
Precision

### ISSUE THREAD

**Issue by VladIacobIonut** [maitek/image_stacking#2]
Hello,

Did you managed to allign the two pictures at pixel level? As in, make every pixel in the second image shift to the same position of the same pixel in the original image ??

Thank you.

**Comment by maitek** [comment]
The images are alligned to each other by warping one image to the other using a perspective transform. It is able to correct for small movement of the camera but will fail for large camera movement, or for moving objects.

**Comment by VladIacobIonut** [comment]
I managed to corect the perspective myself using the warping. However I am aiming for a 1-1 transformation where pixels in the two images match so I to find the differences between the two images. Do you have a suggestion for how this could be accomplished? Does it even worth the bother to try allign the images perfectly using warpPerspective?

Thank you.

Vlad Iacob
Cluj-Napoca, Romania.


On 19 Nov 2018, at 22:22, Mathias Sundholm <notifications@github.com<mailto:notifications@github.com>> wrote:


The images are alligned to each other by warping one image to the other using a perspective transform. It is able to correct for small movement of the camera but will fail for large camera movement, or for moving objects.

**Comment by maitek** [comment]
If I understand your problem correctly, you could first align your two images using warpPerspective, and then calculate a pixelwise distance between them:

`dist_img = (img1-img2)**2`

Pixels that differs between the two images will have a large distance.
