### ISSUE TITLE
[FYI] Rust port

### ISSUE THREAD

**Issue by eadf** [maitek/image_stacking#5]
I've ported your code to Rust [here: github.com/eadf/libstacker.rs](https://github.com/eadf/libstacker.rs)
There are still things I need to figure out, but it is a start.

I didn't see any license in your code so I just slapped the Rust default MIT/Apache license on my port.
Let me know if you have any objections.

I welcome feedback

**Comment by maitek** [comment]
Cool, nice project! That is totally fine. I now added the MIT licence to this project as well for anyone else who would like to use it.
